require("themery").setup({
    themes = {
        "kanagawa",
        "kanagawa-lotus",
        "kanagawa-wave",
        "kanagawa-dragon",
        "catppuccin-mocha",
        "catppuccin-macchiato",
        "catppuccin-frappe",
        "tokyonight-day",
        "tokyonight-moon",
        "tokyonight-night",
        "tokyonight-storm",
        "tokyonight",
        "yowish",
        "oldworld",
    },
    themeConfigFile = "~/.config/nvim/lua/settings/theme.lua",
    livePreview = true,
})
